version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest 
    ports:
      - '5432:5432' # indica as portas usadas pelo postgres
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql 
      # persiste os dados mesmo com a máquina desligada

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # permite não usar senhas
    ports:
      - '6379:6379'
    volumes:
      - 'polls_redis_data:/bitnami/redis/data'

volumes:
  polls_pg_data:
  polls_redis_data: